safe: true
future: true
exclude: [.gitattributes, .gitignore, .idea, .run, README.md, CNAME, docker-compose.yml, Dockerfile]
boxfuseVersion: 1.37.0.2024
highlighter: rouge
url: https://cloudcaptain.sh
